project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    background: primary
    search: true
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 1: Layered Grammar of Graphics"
            href: "Hands-On_Ex/Hands-on_Ex01/Hands-on_Ex01.qmd"
          - text: "Hands-on Exercise 2: Beyond ggplot2 Fundamentals"
            href: "Hands-On_Ex/Hands-on_Ex02/Hands-on_Ex02.qmd"
          - text: "Hands-on Exercise 3A: Interactive Data Visualisation"
            href: "Hands-On_Ex/Hands-on_Ex03/Hands-on_Ex03A.qmd"
          - text: "Hands-on Exercise 3B: Animated Statistical Graphics"
            href: "Hands-On_Ex/Hands-on_Ex03B/Hands-on_Ex03B.qmd"
          - text: "Hands-on Exercise 4A: Fundamentals of Visual Analytics"
            href: "Hands-On_Ex/Hands-on_Ex04/Hands-on_Ex04A.qmd"
          - text: "Hands-on Exercise 4B: Visual Statistical Analysis"
            href: "Hands-On_Ex/Hands-on_Ex04/Hands-on_Ex04B.qmd"
          - text: "Hands-on Exercise 4C: Visualising Uncertainty"
            href: "Hands-On_Ex/Hands-on_Ex04/Hands-on_Ex04C.qmd"
          - text: "Hands-on Exercise 4D: Funnel Plots"
            href: "Hands-On_Ex/Hands-on_Ex04/Hands-on_Ex04D.qmd"
          - text: "Hands-on Exercise 5A: Creating Ternary Plot with R"
            href: "Hands-On_Ex/Hands-on_Ex05/Hands-on_Ex05A.qmd"
          - text: "Hands-on Exercise 5B: Visual Correlation Analysis"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05B.qmd"
          - text: "Hands-on Exercise 5C: Heatmap for Visualising Multivariate Data"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05C.qmd"
          - text: "Hands-on Exercise 5D: Parallel Coordinates Plot"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05D.qmd"

      - text: "Take-Home Exercise"
        menu:
          - text: "Technical Report"
            href: "Take-Home_Ex/Ex01/Ex01_Technical.qmd"
          - text: "Executive Report"
            href: "Take-Home_Ex/Ex01/Ex01_Executive.qmd"

    right:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual